version: "3"

services:
  mongodb-web:
    image: mongodb-example
    ports: 
      - "8080:8080"
#     networks:
#       - mongodb_net
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - /home/docker/mongo-data:./data/db
#     networks:
#       - mongodb_net
# networks:
#   mongodb_net:
